### PR TITLE
Wafertest

### PR DESCRIPTION
**Pull request by cfangmeier**

### CODE REVIEW

**Comment by meierb** [comment]
Caleb,

I think you have a 64 bit compiler. Otherwise your modification in the USB Library makes 
no sense. With my 32 bit Windows compiler, I get exactly the same code. But I found a much 
more serious problem that can cause problems on Linux systems. In linux/WinTypes.h there 
is a typedef

typedef unsigned long DWORD;

DWORD is by definition a 32 bit integer in Windows (32/64bit). But on 64 bit systems long 
is 64 bit.

I replaced ftd2xx.h and WinTypes.h by the newest version. There DWORD is defined the 
correct way:

typedef unsigned int            DWORD;

I dont know if you have to replace the ftdi library by the newest version.

Beat

Am 08.08.2013 20:01, schrieb Caleb Fangmeier:

> ---
> 
> ```
>     You can merge this Pull Request by running
> ```
> 
>    git pull https://github.com/cfangmeier/psi46test wafertest
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/frmeier/psi46test/pull/3
> 
> ```
>     Commit Summary
> ```
> - Fixed errors caused by optimization on Ubuntu by disabling it. Also, fixed
> - Merge branch 'wafertest' of https://github.com/frmeier/psi46test into wafertest
>   
>   ```
>   File Changes
>   ```
> - _M_ Makefile https://github.com/frmeier/psi46test/pull/3/files#diff-0 (2)
> - _M_ usb.cpp https://github.com/frmeier/psi46test/pull/3/files#diff-1 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/frmeier/psi46test/pull/3.patch
> - https://github.com/frmeier/psi46test/pull/3.diff

**Comment by meierb** [comment]
I think, we should fix this optimization problem. Maybe, this has something to do with my 
previous comment. Can you set this parameter to -O1 ?

Beat

Am 08.08.2013 20:01, schrieb Caleb Fangmeier:

> ---
> 
> ```
>     You can merge this Pull Request by running
> ```
> 
>    git pull https://github.com/cfangmeier/psi46test wafertest
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/frmeier/psi46test/pull/3
> 
> ```
>     Commit Summary
> ```
> - Fixed errors caused by optimization on Ubuntu by disabling it. Also, fixed
> - Merge branch 'wafertest' of https://github.com/frmeier/psi46test into wafertest
>   
>   ```
>   File Changes
>   ```
> - _M_ Makefile https://github.com/frmeier/psi46test/pull/3/files#diff-0 (2)
> - _M_ usb.cpp https://github.com/frmeier/psi46test/pull/3/files#diff-1 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/frmeier/psi46test/pull/3.patch
> - https://github.com/frmeier/psi46test/pull/3.diff

**Comment by frmeier** [comment]
Hi Beat

I already tried -O1 and it fails. With some more gdb I found out that it
fails when reading the filename from the command line. There you use
sprintf. I'm trying to replace this with more C++-style commands and
will report my findings later.

Cheers,

Frank

On 8.08.13 17:09, meierb wrote:

> I think, we should fix this optimization problem. Maybe, this has
> something to do with my
> previous comment. Can you set this parameter to -O1 ?
> 
> Beat
> 
> Am 08.08.2013 20:01, schrieb Caleb Fangmeier:
> 
> > ---
> > 
> > You can merge this Pull Request by running
> > 
> > git pull https://github.com/cfangmeier/psi46test wafertest
> > 
> > Or view, comment on, or merge it at:
> > 
> > https://github.com/frmeier/psi46test/pull/3
> > 
> > Commit Summary
> > - Fixed errors caused by optimization on Ubuntu by disabling it. Also,
> >   fixed
> > - Merge branch 'wafertest' of https://github.com/frmeier/psi46test
> >   into wafertest
> > 
> > File Changes
> > - _M_ Makefile
> >   https://github.com/frmeier/psi46test/pull/3/files#diff-0 (2)
> > - _M_ usb.cpp
> >   https://github.com/frmeier/psi46test/pull/3/files#diff-1 (2)
> > 
> > Patch Links:
> > - https://github.com/frmeier/psi46test/pull/3.patch
> > - https://github.com/frmeier/psi46test/pull/3.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frmeier/psi46test/pull/3#issuecomment-22361870.

## 

Frank Meier Aeschbacher
University of Nebraska-Lincoln
Jorgensen Hall, 855 N 16th Street
Lincoln, NE 68588-0299
office +1-402-472-9181, cell +1-402-613-5770
frank.meier@unl.edu, frmeier@cern.ch

**Comment by meierb** [comment]
I cannot find this "sprintf" in the source. Can you tell me in which file and line you found it?

**Comment by frmeier** [comment]
It is now fixed with commit ac0f2a6. But take care: Strange enough the
commit on the github website shows a bunch of stuff that you checked in.
My only change is the one to psi46test.cpp. But you covered that by
changing line 49/50 to "strncpy(filename, argv[1], sizeof(filename)); ".

Strange.

My comment on sprintf was misleading, I meant strncpy, but wrote that
comment while I was distracted with other tedious stuff. I'm not used to
strncpy et.al. - was raised later ;)

I have to check the status of the repository. I might have accidentally
created a mess...

On 8.08.13 18:05, meierb wrote:

> I cannot find this "sprintf" in the source. Can you tell me in which
> file and line you found it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frmeier/psi46test/pull/3#issuecomment-22364862.

## 

Frank Meier Aeschbacher
University of Nebraska-Lincoln
Jorgensen Hall, 855 N 16th Street
Lincoln, NE 68588-0299
office +1-402-472-9181, cell +1-402-613-5770
frank.meier@unl.edu, frmeier@cern.ch

**Pull request merged**
